# FILE: pubspec.yaml 

name: robot_wifi_control
description: A Flutter app to control an ESP32 robot over WiFi (HTTP / WebSocket)
publish_to: "none"
version: 0.0.1
environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  http: ^0.13.6
  web_socket_channel: ^2.3.0
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0  # Ajoutez cette ligne

flutter:
  uses-material-design: true
  # assets:  # Commenté car le dossier n'existe pas
  #   - assets/icons/

